[Icon Theme]
Name=Lucid
Comment=LucidOS Icon Theme
Example=folder
Inherits=Lucid-Everything,Adwaita

DisplayDepth=32
LinkOverlay=link_overlay
LockOverlay=lock_overlay
ZipOverlay=zip_overlay

DesktopDefault=48
DesktopSizes=512,256,128,64,48,32,24,16
ToolbarDefault=24
ToolbarSizes=512,256,128,64,48,32,24,16
MainToolbarDefault=24
MainToolbarSizes=512,256,128,64,48,32,24,16
SmallDefault=16
SmallSizes=16
PanelDefault=32
PanelSizes=512,256,128,64,48,32,24,16

# Directories listed from largest to smallest to prefer bigger icons
Directories=512x512/apps,512x512/mimetypes,256x256/apps,128x128/apps,64x64/apps,24x24/status,16x16/status,scalable/apps,scalable/devices,scalable/mimetypes,scalable/places,scalable/status,symbolic/actions

[16x16/actions]
Context=Actions
Size=16
Type=Fixed

[16x16/apps]
Context=Applications
Size=16
Type=Fixed

[16x16/categories]
Context=Categories
Size=16
Type=Fixed

[16x16/devices]
Context=Devices
Size=16
Type=Fixed

[16x16/emblems]
Context=Emblems
Size=16
Type=Fixed

[16x16/emotes]
Context=Emotes
Size=16
Type=Fixed

[16x16/mimetypes]
Context=MimeTypes
Size=16
Type=Fixed

[16x16/places]
Context=Places
Size=16
Type=Fixed

[16x16/status]
Context=Status
Size=16
Type=Fixed

[16x16/ui]
Context=UI
Size=16
Type=Fixed

################################
# 24x24
################################

[24x24/actions]
Context=Actions
Size=24
Type=Fixed

[24x24/apps]
Context=Applications
Size=24
Type=Fixed

[24x24/categories]
Context=Categories
Size=24
Type=Fixed

[24x24/devices]
Context=Devices
Size=24
Type=Fixed

[24x24/emblems]
Context=Emblems
Size=24
Type=Fixed

[24x24/emotes]
Context=Emotes
Size=24
Type=Fixed

[24x24/mimetypes]
Context=MimeTypes
Size=24
Type=Fixed

[24x24/places]
Context=Places
Size=24
Type=Fixed

[24x24/status]
Context=Status
Size=24
Type=Fixed

[24x24/ui]
Context=UI
Size=24
Type=Fixed


################################
# 32x32
################################

[32x32/actions]
Context=Actions
Size=32
Type=Fixed

[32x32/apps]
Context=Applications
Size=32
Type=Fixed

[32x32/categories]
Context=Categories
Size=32
Type=Fixed

[32x32/devices]
Context=Devices
Size=32
Type=Fixed

[32x32/emblems]
Context=Emblems
Size=32
Type=Fixed

[32x32/emotes]
Context=Emotes
Size=32
Type=Fixed

[32x32/mimetypes]
Context=MimeTypes
Size=32
Type=Fixed

[32x32/places]
Context=Places
Size=32
Type=Fixed

[32x32/status]
Context=Status
Size=32
Type=Fixed

[32x32/ui]
Context=UI
Size=32
Type=Fixed


################################
# 48x48
################################

[48x48/actions]
Context=Actions
Size=48
Type=Fixed

[48x48/apps]
Context=Applications
Size=48
Type=Fixed

[48x48/categories]
Context=Categories
Size=48
Type=Fixed

[48x48/devices]
Context=Devices
Size=48
Type=Fixed

[48x48/emblems]
Context=Emblems
Size=48
Type=Fixed

[48x48/emotes]
Context=Emotes
Size=48
Type=Fixed

[48x48/mimetypes]
Context=MimeTypes
Size=48
Type=Fixed

[48x48/places]
Context=Places
Size=48
Type=Fixed

[48x48/status]
Context=Status
Size=48
Type=Fixed

[48x48/ui]
Context=UI
Size=48
Type=Fixed


################################
# 64x64
################################

[64x64/actions]
Context=Actions
Size=64
Type=Fixed

[64x64/apps]
Context=Applications
Size=64
Type=Fixed

[64x64/categories]
Context=Categories
Size=64
Type=Fixed

[64x64/devices]
Context=Devices
Size=64
Type=Fixed

[64x64/emblems]
Context=Emblems
Size=64
Type=Fixed

[64x64/emotes]
Context=Emotes
Size=64
Type=Fixed

[64x64/mimetypes]
Context=MimeTypes
Size=64
Type=Fixed

[64x64/places]
Context=Places
Size=64
Type=Fixed

[64x64/status]
Context=Status
Size=64
Type=Fixed

[64x64/ui]
Context=UI
Size=64
Type=Fixed


################################
# 128x128
################################

[128x128/actions]
Context=Actions
Size=128
Type=Fixed

[128x128/apps]
Context=Applications
Size=128
Type=Fixed

[128x128/categories]
Context=Categories
Size=128
Type=Fixed

[128x128/devices]
Context=Devices
Size=128
Type=Fixed

[128x128/emblems]
Context=Emblems
Size=128
Type=Fixed

[128x128/emotes]
Context=Emotes
Size=128
Type=Fixed

[128x128/mimetypes]
Context=MimeTypes
Size=128
Type=Fixed

[128x128/places]
Context=Places
Size=128
Type=Fixed

[128x128/status]
Context=Status
Size=128
Type=Fixed

[128x128/ui]
Context=UI
Size=128
Type=Fixed


################################
# 256x256
################################

[256x256/actions]
Context=Actions
Size=256
Type=Fixed

[256x256/apps]
Context=Applications
Size=256
Type=Fixed

[256x256/categories]
Context=Categories
Size=256
Type=Fixed

[256x256/devices]
Context=Devices
Size=256
Type=Fixed

[256x256/emblems]
Context=Emblems
Size=256
Type=Fixed

[256x256/emotes]
Context=Emotes
Size=256
Type=Fixed

[256x256/mimetypes]
Context=MimeTypes
Size=256
Type=Fixed

[256x256/places]
Context=Places
Size=256
Type=Fixed

[256x256/status]
Context=Status
Size=256
Type=Fixed

[256x256/ui]
Context=UI
Size=256
Type=Fixed


################################
# 512x512
################################

[512x512/actions]
Context=Actions
Size=512
Type=Fixed

[512x512/apps]
Context=Applications
Size=512
Type=Fixed

[512x512/categories]
Context=Categories
Size=512
Type=Fixed

[512x512/devices]
Context=Devices
Size=512
Type=Fixed

[512x512/emblems]
Context=Emblems
Size=512
Type=Fixed

[512x512/emotes]
Context=Emotes
Size=512
Type=Fixed

[512x512/mimetypes]
Context=MimeTypes
Size=512
Type=Fixed

[512x512/places]
Context=Places
Size=512
Type=Fixed

[512x512/status]
Context=Status
Size=512
Type=Fixed

[512x512/ui]
Context=UI
Size=512
Type=Fixed

[scalable/apps]
Context=Applications
Size=64
MinSize=16
MaxSize=512
Type=Scalable

[scalable/devices]
Context=Devices
Size=64
MinSize=16
MaxSize=512
Type=Scalable

[scalable/mimetypes]
Context=MimeTypes
Size=64
MinSize=16
MaxSize=512
Type=Scalable

[scalable/places]
Context=Places
Size=64
MinSize=16
MaxSize=512
Type=Scalable

[scalable/status]
Context=Status
Size=64
MinSize=16
MaxSize=512
Type=Scalable

[symbolic/actions]
Context=Actions
Size=16
MinSize=8
MaxSize=512
Type=Scalable
